kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.component_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
    spec:
      containers:
        - name: ${{ values.component_id }}
          image: quay.io/${{ values.imageregistry }}/${{ values.component_id }}:latest
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
