kind: Service
apiVersion: v1
metadata:
  name: ${{ values.component_id }}
spec:
  ports:
    - name: http-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ${{ values.component_id }}
